import inquirer from "inquirer";
import chalk from "chalk";
import ora from "ora";
import figlet from "figlet";
import { writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { setupPrompts, type SetupAnswers } from "./prompts.js";
import { SAMPLE_NOTEBOOK_URL, getSampleNotebookConfig } from "./sample-notebook.js";

export interface SetupConfig {
  notebook: {
    url: string;
    isDemo: boolean;
  };
  logging: {
    level: string;
  };
  browser: {
    headless: boolean;
  };
  quota: {
    limit: number;
  };
  createdAt: string;
}

/**
 * Run the interactive setup wizard (HARD-12).
 */
export async function runSetupWizard(basePath: string = process.cwd()): Promise<SetupConfig> {
  // Display welcome banner
  displayWelcomeBanner();

  // Run interactive prompts
  const answers = await inquirer.prompt<SetupAnswers>(setupPrompts);

  // Build configuration
  const config = buildConfig(answers);

  // Save configuration with spinner
  const spinner = ora("Saving configuration...").start();

  try {
    await saveConfiguration(config, basePath);
    spinner.succeed(chalk.green("Configuration saved to .msw/config.yaml"));
  } catch (error) {
    spinner.fail(chalk.red("Failed to save configuration"));
    throw error;
  }

  // Display demo mode info if applicable
  if (config.notebook.isDemo) {
    displayDemoModeInfo();
  }

  console.log("");
  console.log(chalk.green("Setup complete! Run `msw start` to begin."));
  console.log("");

  return config;
}

function displayWelcomeBanner(): void {
  console.log("");
  console.log(
    chalk.cyan(
      figlet.textSync("MSW Protocol", { horizontalLayout: "default" })
    )
  );
  console.log(chalk.gray("  Make Shit Work - NotebookLM Integration"));
  console.log(chalk.gray("  Zero manual copy-paste between NotebookLM and coding agents"));
  console.log("");
}

function displayDemoModeInfo(): void {
  console.log("");
  console.log(chalk.yellow("=== Demo Mode ==="));
  console.log(chalk.gray("You are running in demo mode with a sample notebook."));
  console.log(chalk.gray("This provides safe, read-only access to test MSW features:"));
  console.log("");

  const features = getSampleNotebookConfig().features;
  for (const feature of features) {
    console.log(chalk.gray(`  - ${feature}`));
  }

  console.log("");
  console.log(chalk.gray("To use your own notebook, run `msw setup` again."));
}

function buildConfig(answers: SetupAnswers): SetupConfig {
  const isDemo = answers.useDemo;

  return {
    notebook: {
      url: isDemo ? SAMPLE_NOTEBOOK_URL : answers.notebookUrl,
      isDemo,
    },
    logging: {
      level: answers.logLevel,
    },
    browser: {
      headless: answers.headless,
    },
    quota: {
      limit: answers.quotaLimit,
    },
    createdAt: new Date().toISOString(),
  };
}

async function saveConfiguration(config: SetupConfig, basePath: string): Promise<void> {
  const configPath = join(basePath, ".msw/config.yaml");
  const dir = dirname(configPath);

  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  // Convert to YAML format manually (avoid yaml dependency for now)
  const yaml = configToYaml(config);
  writeFileSync(configPath, yaml, "utf-8");
}

function configToYaml(config: SetupConfig): string {
  return `# MSW Protocol Configuration
# Generated by setup wizard

notebook:
  url: "${config.notebook.url}"
  isDemo: ${config.notebook.isDemo}

logging:
  level: "${config.logging.level}"

browser:
  headless: ${config.browser.headless}

quota:
  limit: ${config.quota.limit}

# Metadata
createdAt: "${config.createdAt}"
`;
}
