name: 'Setup Node with Cache'
description: 'Setup Node.js with npm cache and install dependencies'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '20.x'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci
